# Generated by Django 4.2.1 on 2024-03-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonSectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('last_time_accessed', models.DateTimeField()),
                ('last_time_updated', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyPlayVideoCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('play_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecificVideoInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.CharField(max_length=100)),
                ('students_visits_count', models.IntegerField()),
                ('viewing_percent_median', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoSectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('last_time_accessed', models.DateTimeField()),
                ('last_time_updated', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
