# Generated by Django 4.2.1 on 2024-04-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosectionreport',
            name='course_id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
