# Generated by Django 4.2.1 on 2024-05-10 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='sectionactivity',
            name='section_type',
            field=models.CharField(choices=[('common', 'common'), ('video', 'video'), ('pdf', 'pdf'), ('forum', 'forum'), ('pages', 'pages'), ('tasks', 'tasks'), ('students', 'students')], max_length=10),
        ),
        migrations.CreateModel(
            name='StudentsSectionReport',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses.course')),
                ('last_time_accessed', models.DateTimeField(default=datetime.datetime.now)),
                ('last_time_updated', models.DateTimeField(default=datetime.datetime.now)),
                ('report_state', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('done', 'Created'), ('failed', 'Failed')], default='not_started', max_length=12)),
                ('error_code', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('done', 'Created'), ('failed', 'Failed')], default=None, max_length=50, null=True)),
                ('students_chart', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='metrics.studentschart')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField()),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('total_hours', models.PositiveIntegerField(default=0)),
                ('textbook_views', models.PositiveIntegerField(default=0)),
                ('solved_tasks', models.PositiveIntegerField(default=0)),
                ('average_attempt_count', models.PositiveIntegerField(default=0)),
                ('forum_activity', models.PositiveIntegerField(default=0)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='metrics.studentschart')),
            ],
        ),
    ]
