# Generated by Django 4.2.1 on 2024-03-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyPlayVideoCount',
        ),
        migrations.DeleteModel(
            name='SpecificVideoInteraction',
        ),
    ]
