# Generated by Django 4.2.1 on 2024-04-01 15:47

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_alter_videosectionreport_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionDegreeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SectionActivityChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SessionTimeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SessionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('browser', 'Browser'), ('mobile', 'Mobile'), ('all', 'All types')], default='all', max_length=10)),
                ('average_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='metrics.sessiontimechart')),
            ],
        ),
        migrations.CreateModel(
            name='SectionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('common', 'common'), ('video', 'video'), ('pdf', 'pdf'), ('forum', 'forum'), ('pages', 'pages'), ('tasks', 'tasks')], max_length=10)),
                ('students_percent', models.IntegerField()),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='metrics.sectionactivitychart')),
            ],
        ),
        migrations.CreateModel(
            name='CompletionDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_degree', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=12)),
                ('students_count', models.IntegerField()),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='metrics.completiondegreechart')),
            ],
        ),
        migrations.CreateModel(
            name='CommonSectionReport',
            fields=[
                ('course_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('last_time_accessed', models.DateTimeField(default=datetime.datetime.now)),
                ('last_time_updated', models.DateTimeField(default=datetime.datetime.now)),
                ('report_state', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('done', 'Created'), ('failed', 'Failed')], max_length=12)),
                ('error_reason', models.CharField(default=None, max_length=100, null=True)),
                ('completion_degree_chart', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='metrics.completiondegreechart')),
                ('section_activity_chart', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='metrics.sectionactivitychart')),
                ('session_time_chart', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='metrics.sessiontimechart')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
