# Generated by Django 4.2.1 on 2024-03-29 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_delete_dailyplayvideocount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonsectionreport',
            name='common_report_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='commonsectionreport',
            name='report_state',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('done', 'Created'), ('failed', 'Failed')], default='not_started', max_length=12),
        ),
        migrations.AddField(
            model_name='videosectionreport',
            name='report_state',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('done', 'Created'), ('failed', 'Failed')], default='not_started', max_length=12),
        ),
        migrations.AddField(
            model_name='videosectionreport',
            name='video_report_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='commonsectionreport',
            name='last_time_accessed',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='commonsectionreport',
            name='last_time_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='videosectionreport',
            name='last_time_accessed',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='videosectionreport',
            name='last_time_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
