# Generated by Django 4.2.1 on 2024-03-30 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_commonsectionreport_common_report_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('section_type', models.CharField(choices=[('common', 'common'), ('video', 'video'), ('pdf', 'pdf'), ('forum', 'forum'), ('pages', 'pages'), ('tasks', 'tasks')], max_length=10)),
                ('last_time_accessed', models.DateTimeField(default=datetime.datetime.now)),
                ('last_time_updated', models.DateTimeField(default=datetime.datetime.now)),
                ('report_state', models.CharField(choices=[('in_progress', 'In progress'), ('done', 'Created'), ('failed', 'Failed')], max_length=12)),
                ('report_data', models.JSONField(default=dict)),
            ],
            options={
                'unique_together': {('course_id', 'section_type')},
            },
        ),
        migrations.DeleteModel(
            name='CommonSectionReport',
        ),
        migrations.DeleteModel(
            name='VideoSectionReport',
        ),
    ]
