# Generated by Django 4.2.1 on 2024-04-01 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_completiondegreechart_sectionactivitychart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonsectionreport',
            name='completion_degree_chart',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='metrics.completiondegreechart'),
        ),
        migrations.AlterField(
            model_name='commonsectionreport',
            name='report_state',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('done', 'Created'), ('failed', 'Failed')], default='not_started', max_length=12),
        ),
        migrations.AlterField(
            model_name='commonsectionreport',
            name='section_activity_chart',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='metrics.sectionactivitychart'),
        ),
        migrations.AlterField(
            model_name='commonsectionreport',
            name='session_time_chart',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='metrics.sessiontimechart'),
        ),
        migrations.AlterField(
            model_name='videosectionreport',
            name='report_state',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('done', 'Created'), ('failed', 'Failed')], default='not_started', max_length=12),
        ),
        migrations.AlterField(
            model_name='videosectionreport',
            name='video_interaction_chart',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='metrics.videointeractionchart'),
        ),
        migrations.AlterField(
            model_name='videosectionreport',
            name='video_play_count_chart',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='metrics.videoplaycountchart'),
        ),
    ]
