# Generated by Django 4.2.1 on 2024-05-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_studentdata_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomplexity',
            name='question',
            field=models.CharField(default='', max_length=150),
        ),
    ]
