# Generated by Django 4.2.1 on 2024-03-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_sectionreport_delete_commonsectionreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionreport',
            name='report_state',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('done', 'Created'), ('failed', 'Failed')], max_length=12),
        ),
    ]
