# Generated by Django 4.2.1 on 2024-04-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_alter_commonsectionreport_completion_degree_chart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontime',
            name='average_time',
            field=models.IntegerField(),
        ),
    ]
