# Generated by Django 4.2.1 on 2024-05-10 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_taskcomplexity_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('video_interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='metrics.videointeraction')),
            ],
        ),
    ]
