# Generated by Django 4.2.1 on 2024-04-12 12:46

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_alter_sessiontime_average_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskComplexityChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSummaryChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_count', models.CharField(choices=[('first', 'First attempt'), ('second', 'Second attempt'), ('more', 'Third attempt and more')])),
                ('percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='metrics.tasksummarychart')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSectionReport',
            fields=[
                ('course_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('last_time_accessed', models.DateTimeField(default=datetime.datetime.now)),
                ('last_time_updated', models.DateTimeField(default=datetime.datetime.now)),
                ('report_state', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('done', 'Created'), ('failed', 'Failed')], default='not_started', max_length=12)),
                ('error_reason', models.CharField(default=None, max_length=100, null=True)),
                ('task_complexity_chart', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='metrics.taskcomplexitychart')),
                ('task_summary_chart', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='metrics.tasksummarychart')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskComplexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_link', models.CharField(max_length=250)),
                ('all_attempts', models.IntegerField()),
                ('successful_attempts', models.IntegerField()),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='metrics.taskcomplexitychart')),
            ],
        ),
    ]
