# Generated by Django 4.2.1 on 2024-05-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0006_remove_taskcomplexity_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomplexity',
            name='question',
            field=models.CharField(default='', max_length=150),
        ),
    ]
