# Generated by Django 4.2.1 on 2024-04-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0006_taskcomplexitychart_tasksummarychart_tasksummary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videointeraction',
            old_name='students_visits_count',
            new_name='views_count',
        ),
    ]
