# Generated by Django 4.2.1 on 2024-04-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_rename_students_visits_count_videointeraction_views_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videointeraction',
            old_name='viewing_percent_median',
            new_name='unique_students_count',
        ),
    ]
