# Generated by Django 4.2.1 on 2024-05-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0008_videointeraction_popular_intervals_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videointeraction',
            old_name='popular_intervals',
            new_name='popular_fragments',
        ),
    ]
