# Generated by Django 4.2.1 on 2024-04-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0009_forumquestionchart_pagespopularitychart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumquestion',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='forumquestion',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
