# Generated by Django 4.2.1 on 2024-04-13 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0010_forumquestion_body_alter_forumquestion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagespopularity',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='metrics.pagespopularitychart'),
        ),
        migrations.AlterField(
            model_name='textbookviewscount',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='metrics.textbookviewschart'),
        ),
        migrations.AlterField(
            model_name='wordsearchcount',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='metrics.wordsearchchart'),
        ),
    ]
