# Generated by Django 4.2.1 on 2024-04-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0012_alter_videointeraction_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagespopularity',
            name='page_link',
            field=models.CharField(max_length=500),
        ),
    ]
