# Generated by Django 4.2.1 on 2024-04-15 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0014_weeklyactivitycount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonsectionreport',
            name='session_time_chart',
        ),
        migrations.DeleteModel(
            name='SessionTime',
        ),
        migrations.DeleteModel(
            name='SessionTimeChart',
        ),
    ]
