# Generated by Django 4.2.1 on 2024-04-15 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0015_remove_commonsectionreport_session_time_chart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionactivity',
            name='students_percent',
        ),
        migrations.AddField(
            model_name='commonsectionreport',
            name='students_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sectionactivity',
            name='students_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forumquestion',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forumquestion',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pagespopularity',
            name='visits_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tasksummary',
            name='percentage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='textbookviewscount',
            name='unique_students_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='textbookviewscount',
            name='views_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='videointeraction',
            name='unique_students_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='videointeraction',
            name='views_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='videoplaycount',
            name='count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='weeklyactivitycount',
            name='count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='wordsearchcount',
            name='search_count',
            field=models.PositiveIntegerField(),
        ),
    ]
