# Generated by Django 4.2.1 on 2024-04-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0016_remove_sectionactivity_students_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonsectionreport',
            name='error_reason',
        ),
        migrations.RemoveField(
            model_name='forumsectionreport',
            name='error_reason',
        ),
        migrations.RemoveField(
            model_name='pagessectionreport',
            name='error_reason',
        ),
        migrations.RemoveField(
            model_name='tasksectionreport',
            name='error_reason',
        ),
        migrations.RemoveField(
            model_name='textbooksectionreport',
            name='error_reason',
        ),
        migrations.RemoveField(
            model_name='videosectionreport',
            name='error_reason',
        ),
        migrations.AddField(
            model_name='commonsectionreport',
            name='error_code',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('done', 'Created'), ('failed', 'Failed')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='forumsectionreport',
            name='error_code',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('done', 'Created'), ('failed', 'Failed')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagessectionreport',
            name='error_code',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('done', 'Created'), ('failed', 'Failed')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tasksectionreport',
            name='error_code',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('done', 'Created'), ('failed', 'Failed')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='textbooksectionreport',
            name='error_code',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('done', 'Created'), ('failed', 'Failed')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videosectionreport',
            name='error_code',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('done', 'Created'), ('failed', 'Failed')], default=None, max_length=50, null=True),
        ),
    ]
