# Generated by Django 4.2.1 on 2024-04-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0019_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
