# Generated by Django 4.2.1 on 2024-05-09 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('event_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_field', models.JSONField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='courses.course')),
            ],
        ),
    ]
