# Generated by Django 4.2.1 on 2024-04-29 12:36

from django.db import migrations, models
import event_logs.models


class Migration(migrations.Migration):

    dependencies = [
        ('event_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.FileField(upload_to=event_logs.models.PathAndRename('private/log_files/archives'))),
                ('processing_status', models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed')], max_length=15)),
                ('original_log_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
