# Generated by Django 4.2.1 on 2024-04-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('image_url', models.TextField(null=True)),
                ('short_name', models.TextField()),
            ],
        ),
    ]
