name: Python CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.TESTING_POSTGRES_DB }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Env file
      env:
        ENV_FILE: ${{ secrets.ENV_FILE }}
      run: echo $ENV_FILE | base64 --decode > .env

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get install libegl1-mesa
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest
